name: Create PR from dev to master
on:
  push:
    branches:
      - dev

jobs:
  git-pr-release:
    name: git-pr-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: git-pr-release
        uses: bakunyo/git-pr-release-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_CREDENTIALS }}
