name: Json Env Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create json file
        run: |
          echo ${{ secrets.TEST_JSON }} | base64 -d > test.json
      - name: test run
        run: |
          echo ${{ secrets.TEST_JSON }} | base64 -d
      - name: json test run
        run: |
          content=`cat ./test.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=testJson::$content"
